steps:
  # Step 1: Zip the app (excluding this YAML)
  - name: 'ubuntu'
    id: 'Zip app'
    entrypoint: bash
    args:
      - -c
      - |
        apt-get update && apt-get install -y zip
        zip -r app.zip . -x "cloudbuild.yaml"

  # Step 2: Upload the ZIP to Artifact Registry (generic)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Upload to Artifact Registry'
    entrypoint: bash
    args:
      - -c
      - |
        VERSION=$(date +%Y%m%d%H%M%S)
        echo "$VERSION" > /workspace/version.txt
        gcloud artifacts files upload app.zip \
          --project=mythic-beanbag-463309-e9 \
          --location=asia-south1 \
          --repository=generic-repo \
          --package=vm-flask-app \
          --version=$VERSION

  # Step 3: Create the VM (if it doesn't exist)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create VM if needed'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute instances describe app-vm --zone=asia-south1-a --project=mythic-beanbag-463309-e9 >/dev/null 2>&1 || \
        gcloud compute instances create app-vm \
          --zone=asia-south1-a \
          --machine-type=e2-micro \
          --image-family=debian-11 \
          --image-project=debian-cloud \
          --boot-disk-size=20GB \
          --tags=http-server \
          --scopes=https://www.googleapis.com/auth/cloud-platform \
          --service-account=956387703564-compute@developer.gserviceaccount.com@mythic-beanbag-463309-e9.iam.gserviceaccount.com

  # Step 4: Create the startup script
  - name: 'ubuntu'
    id: 'Create startup.sh'
    entrypoint: bash
    args:
      - -c
      - |
        VERSION=$(cat /workspace/version.txt)
        cat << 'EOF' > /workspace/startup.sh
        #!/bin/bash
        set -e

        sudo apt-get update
        sudo apt-get install -y unzip curl python3 python3-pip

        VERSION=$(cat /home/USER/version.txt)

        curl -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -o app.zip \
          "https://asia-south1-artifactregistry.googleapis.com/v1/projects/YOUR_PROJECT_ID/locations/asia-south1/repositories/generic-repo/packages/vm-flask-app/versions/\${VERSION}/files/app.zip?alt=media"

        unzip -o app.zip -d app-dir
        cd app-dir
        pip3 install -r requirements.txt
        nohup python3 main.py > app.log 2>&1 &
        EOF
  # Step 5: Copy script and version.txt to VM
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Copy to VM'
    args:
      - compute
      - scp
      - /workspace/startup.sh
      - /workspace/version.txt
      - praveen_a@app-vm:/home/praveen_a
      - --zone=asia-south1-a
      - --project=mythic-beanbag-463309-e9

  # Step 6: SSH to run the script
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Run on VM'
    args:
      - compute
      - ssh
      - praveen_a@app-vm
      - --zone=asia-south1-a
      - --project=mythic-beanbag-463309-e9
      - --command=bash /home/praveen_a/startup.sh

options:
  logging: CLOUD_LOGGING_ONLY
